queue:
  name: Hosted VS2017
  demands: npm

trigger:
- master
- release
- develop

steps:
- task: gittools.gitversion.gitversion-task.GitVersion@3

- task: Npm@1
  inputs:
    command: "install"
    verbose: "false"
    workingDir: "core"

- task: Npm@1
  inputs:
    command: "custom"
    verbose: "false"
    customCommand: "run build"
    workingDir: "core"

- powershell: . 'core/update-package-version.ps1' $(GitVersion.SemVer) 
  displayName: Update package version

- task: Npm@1
  inputs:
    command: "install"
    verbose: "false"
    workingDir: "functions"

- task: Npm@1
  inputs:
    command: "custom"
    verbose: "false"
    customCommand: "run build"
    workingDir: "functions"

- powershell: . 'functions/update-package-version.ps1' $(GitVersion.SemVer) 
  displayName: Update package version

- task: Npm@1
  displayName: npm custom
  inputs:
    command: custom
    workingDir: core
    verbose: false
    customCommand: 'publish --access public'
    customEndpoint: npm
    publishEndpoint: npm
    condition: and(succeeded(), eq(variables['DEPLOY_NPM'], 'true'))

- task: Npm@1
  displayName: npm custom
  inputs:
    command: custom
    workingDir: functions
    verbose: false
    customCommand: 'publish --access public'
    customEndpoint: npm
    publishEndpoint: npm
    condition: and(succeeded(), eq(variables['DEPLOY_NPM'], 'true'))

- task: Npm@1
  inputs:
    command: "install"
    verbose: "false"
    workingDir: "docs-app"

- task: Npm@1
  inputs:
    command: "custom"
    verbose: "false"
    customCommand: "run build"
    workingDir: "docs-app"

# - task: sergeyzwezdin.magic-chunks.magic.chunks.MagicChunks@2
#   displayName: Config transform - dfsdf
#   inputs:
#     sourcePath: dfsdf
#     transformations: |
#      {
#        "projects": {
#          "default": "$(FIREBASE_PROJECT_NAME)"
#        }
#      }
