queue:
  name: Hosted VS2017
  demands: npm

trigger:
- master
- release
- develop

steps:
- task: gittools.gitversion.gitversion-task.GitVersion@3

- task: Npm@1
  inputs:
    command: "install"
    verbose: "false"
    workingDir: "core"

- task: Npm@1
  inputs:
    command: "custom"
    verbose: "false"
    customCommand: "run build"
    workingDir: "core"

- powershell: . 'core/update-package-version.ps1' $(GitVersion.SemVer) 
  displayName: Update package version

- script: 'echo "//registry.npmjs.org/:_authToken=$(NPM_TOKEN)" >> ~/.npmrc' core 
  displayName: Command Line Script

- task: Npm@1
  inputs:
    command: "install"
    verbose: "false"
    workingDir: "functions"

- task: Npm@1
  inputs:
    command: "custom"
    verbose: "false"
    customCommand: "run build"
    workingDir: "functions"

- powershell: . 'functions/update-package-version.ps1' $(GitVersion.SemVer) 
  displayName: Update package version

- script: 'echo "//registry.npmjs.org/:_authToken=$(NPM_TOKEN)" >> ~/.npmrc' functions 
  displayName: Command Line Script



