version: "3"
services:
  mongo:
    image: mongo
    expose: 
      - 27018
    ports:
      - "27018:27017"
    volumes:
      - mongodata:/data/db

  # refract-cms-server:
  #   build: 
  #     context: './packages/server'
  #   links: 
  #     - mongo
  #   expose: 
  #     - 3600
  #   ports:
  #     - "3600:3500"

  mongoexpress:
    image: mongo-express
    ports: 
      - "8091:8081"
    links:
      - mongo

volumes:
  mongodata: