version: "3"
services:
  mongo:
    image: mongo
    expose: 
      - 27018
    ports:
      - "27018:27017"
    volumes:
      - mongodata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=hqXzNv2f5YC45veW

  mongoexpress:
    image: mongo-express
    ports: 
      - "8091:8081"
    links:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_AUTH_USERNAME=root
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=hqXzNv2f5YC45veW
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=hqXzNv2f5YC45veW
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true

volumes:
  mongodata: