version: "3"
services:
  mongo:
    image: mongo
    expose: 
      - 27019
    ports:
      - "27019:27017"
    volumes:
      - mongodata:/data/db

  mongoexpress:
    image: mongo-express
    ports: 
      - "7091:8081"
    links:
      - mongo

volumes:
  mongodata: